# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# Welcome to Jekyll!

remote_theme             : "mmistakes/minimal-mistakes@master"

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "Tsering Sherpa"
title_separator          : "-"
subtitle                 : "Economics PhD Student | Researcher | Mentor"
name                     : "Tsering Sherpa"
description              : "A flexible portfolio site showcasing my research, teaching, and activities."
url                      : "https://tseringsherpa.github.io" # Update this if needed
baseurl                  : "" # Leave empty for GitHub Pages root
repository               : "sherpa5521/tseringsherpa.github.io"
teaser                   : "/assets/images/site-logo.png" # Path to teaser image
logo                     : "/assets/images/logo.png" # Path to logo image
masthead_title           : "" # Use " " for no title
words_per_minute         : 200
enable_copy_code_button  : true

# Navigation Links
header_pages:
  - _pages/about.md
  - _pages/teaching.md
  - _pages/activities.md
  - _pages/publications.md
  - _pages/pets.md
  - _pages/contact.md

# Comments and Analytics
comments:
  provider               : false
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-XXXXXX-X" # Replace with your actual ID
    anonymize_ip         : true

# Search Settings
search                   : true
search_provider          : lunr

# SEO Related
google_site_verification : ""
bing_site_verification   : ""
naver_site_verification  : ""
yandex_site_verification : ""
baidu_site_verification  : ""

# Social Sharing
social:
  type                   : "Person"
  links:
    - "https://linkedin.com/in/tseringlsherpa"
    - "https://github.com/sherpa5521"

# Author Information
author:
  name             : "Tsering Sherpa"
  avatar           : "/assets/images/IMG_5960.jpeg"
  bio              : "Economics PhD student with interests in development, gender studies, and applied econometrics."
  location         : "Seattle, WA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sherpa5521"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/tseringlsherpa"

# Footer Links
footer:
  links:
    - label: "About"
      url: "/about/"
    - label: "Teaching"
      url: "/teaching/"
    - label: "Activities"
      url: "/activities/"
    - label: "Publications"
      url: "/publications/"
    - label: "Pets"
      url: "/pets/"
    - label: "Contact"
      url: "/contact/"

# Defaults for Pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
