remote_theme: "mmistakes/minimal-mistakes@master"
title: "Tsering Sherpa"
description: "Personal website for research and teaching"
url: "https://tseringlsherpa.github.io"
baseurl: "" # Leave empty for personal GitHub Pages
permalink: pretty
