# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.
remote_theme             : "mmistakes/minimal-mistakes@master"

minimal_mistakes_skin    : "default" # Options: "air", "aqua", "contrast", "dark", etc.

# Site Settings
locale                   : "en-US"
title                    : "Tsering Sherpa"
title_separator          : "-"
subtitle                 : "Economics PhD Student | Researcher | Mentor"
name                     : "Tsering Sherpa"
description              : "A portfolio site showcasing my research, teaching, and activities."
url                      : "https://tseringsherpa.github.io" # Ensure this matches your GitHub Pages URL
baseurl                  : "" # Leave empty for personal GitHub Pages
repository               : "sherpa5521/tseringsherpa.github.io"
teaser                   : "/assets/images/site-logo.png" # Path to teaser image
logo                     : "/assets/images/logo.png" # Path to logo image (optional)

# Navigation Links
header_pages:
  - _pages/about.md
  - _pages/teaching.md
  - _pages/activities.md
  - _pages/publications.md
  - _pages/pets.md
  - _pages/contact.md

# Author Information
author:
  name             : "Tsering Sherpa"
  avatar           : "/assets/images/tsering-avatar.jpg" # Path to your avatar image
  bio              : "Economics PhD student with interests in development, gender studies, and applied econometrics."
  location         : "Seattle, WA"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sherpa5521"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/tseringlsherpa"

# Footer Links
footer:
  links:
    - label: "About"
      url: "/about/"
    - label: "Teaching"
      url: "/teaching/"
    - label: "Activities"
      url: "/activities/"
    - label: "Publications"
      url: "/publications/"
    - label: "Pets"
      url: "/pets/"
    - label: "Contact"
      url: "/contact/"

# Search and Analytics
search                   : true
search_provider          : lunr # Options: "lunr" (default), "algolia"
analytics:
  provider               : "google-universal"
  google:
    tracking_id          : "UA-XXXXXX-X" # Replace with your actual Google Analytics ID
    anonymize_ip         : true

# Defaults for Pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
